
export const translations = {
    ar: {
        main_title: "مساعد السهو",
        main_subtitle: "دليلك لمعرفة أحكام سجود السهو في الصلاة.",
        question_type: "ما هو نوع السهو الذي وقعت فيه؟",
        btn_increase: "زيادة",
        btn_decrease: "نقص",
        btn_doubt: "شك",
        q_decrease_type: "ما هو نوع النقص؟",
        q_decrease_desc: "الركن هو جزء أساسي من الصلاة لا تصح إلا به (مثل الركوع والسجود). الواجب هو ما تبطل الصلاة بتركه عمداً لا سهواً (مثل التشهد الأول).",
        btn_decrease_wajib: "نقص واجب",
        btn_decrease_rukn: "نقص ركن",
        q_doubt_type: "هل ترجح لديك أحد الأمرين؟",
        q_doubt_desc: "هل غلب على ظنك عدد معين من الركعات (مثلاً: شعرت بقوة أنك صليت ثلاث ركعات وليس أربع)؟",
        btn_doubt_yes: "نعم، لدي ظن غالب",
        btn_doubt_no: "لا، أنا متردد تماماً",
        result_title: "الحكم الشرعي",
        btn_start_over: "ابدأ من جديد",
        btn_back: "رجوع",
        daleel_title: "الدليل من السنة",
        increase_title: "الحكم في حالة الزيادة",
        increase_details: `<p class="mb-2">إذا زدت في صلاتك ركوعاً أو سجوداً أو ركعة كاملة سهواً، فصلاتك صحيحة.</p><ul class="list-disc list-inside space-y-2"><li>تكمل صلاتك حتى تسلم.</li><li>بعد السلام، تسجد سجدتين للسهو.</li><li>ثم تسلم مرة أخرى.</li></ul>`,
        increase_daleel: `حديث عبد الله بن مسعود رضي الله عنه أن النبي صلى الله عليه وسلم صلى الظهر خمسًا، فقيل له: أزيد في الصلاة؟ قال: "وما ذاك؟" قالوا: صليت خمسًا، فسجد سجدتين بعدما سلم. (متفق عليه).`,
        decrease_wajib_title: "الحكم في حالة نقص واجب",
        decrease_wajib_details: `<p class="mb-2">إذا نسيت واجباً من واجبات الصلاة (مثل التشهد الأول) وذكرته بعد الانتقال للركن الذي يليه، فلا ترجع إليه.</p><ul class="list-disc list-inside space-y-2"><li>تكمل صلاتك بشكل طبيعي.</li><li>قبل أن تسلم، تسجد سجدتين للسهو.</li><li>ثم تسلم.</li></ul>`,
        decrease_wajib_daleel: `حديث عبد الله بن بحينة رضي الله عنه أن النبي صلى الله عليه وسلم قام من اثنتين من الظهر، لم يجلس بينهما، فلما قضى صلاته... سجد سجدتين قبل أن يسلم، ثم سلم. (متفق عليه).`,
        decrease_rukn_title: "الحكم في حالة نقص ركن",
        decrease_rukn_details: `<p class="mb-2 text-red-600 font-semibold">نقص الركن أمر خطير ولا تجبره سجدتا السهو وحدها.</p><p class="mb-2">يجب عليك أن تأتي بالركن الذي نسيته وما بعده. إذا لم تفعل، بطلت صلاتك.</p><ul class="list-disc list-inside space-y-2"><li>إذا ذكرته قبل أن تصل إلى موضعه في الركعة التالية، وجب عليك الرجوع فوراً لتأتي به وبما بعده.</li><li>إذا ذكرته بعد أن وصلت إلى موضعه في الركعة التالية، فإن الركعة التي نسيت فيها الركن تُلغى، وتقوم الركعة الحالية مقامها.</li><li>في كلتا الحالتين، تكمل صلاتك وتسجد للسهو سجدتين قبل السلام.</li></ul>`,
        decrease_rukn_daleel: `قاعدة عامة في الفقه: "الركن لا يسقط بالسهو ولا يُجبر بسجود السهو". ولحديث المسيء صلاته، حيث أمره النبي صلى الله عليه وسلم بإعادة الصلاة لتركه ركناً (الطمأنينة)، ولم يأمره بسجود السهو.`,
        doubt_prevail_title: "الحكم في حالة الشك مع غلبة الظن",
        doubt_prevail_details: `<p class="mb-2">إذا شككت في عدد الركعات ولكن غلب على ظنك شيء معين.</p><ul class="list-disc list-inside space-y-2"><li>تبني على ما غلب على ظنك وتكمل صلاتك.</li><li>بعد أن تسلم، تسجد سجدتين للسهو.</li><li>ثم تسلم مرة أخرى.</li></ul>`,
        doubt_prevail_daleel: `حديث ابن مسعود رضي الله عنه أن النبي صلى الله عليه وسلم قال: "إذا شك أحدكم في صلاته فليتحرَّ الصواب، فليتم عليه، ثم ليسلم، ثم يسجد سجدتين". (متفق عليه).`,
        doubt_no_prevail_title: "الحكم في حالة الشك بدون غلبة الظن",
        doubt_no_prevail_details: `<p class="mb-2">إذا شككت في عدد الركعات ولم يترجح عندك شيء.</p><ul class="list-disc list-inside space-y-2"><li>تبني على اليقين، وهو العدد الأقل (مثلاً، إذا شككت بين الثالثة والرابعة، تعتبرها الثالثة).</li><li>تكمل صلاتك بناءً على ذلك.</li><li>قبل أن تسلم، تسجد سجدتين للسهو.</li><li>ثم تسلم.</li></ul>`,
        doubt_no_prevail_daleel: `حديث أبي سعيد الخدري رضي الله عنه قال: قال رسول الله صلى الله عليه وسلم: "إذا شك أحدكم في صلاته، فلم يدر كم صلى ثلاثًا أم أربعًا؟ فليطرح الشك، وليبن على ما استيقن، ثم يسجد سجدتين قبل أن يسلم...". (رواه مسلم).`,
        
        // Location-related translations
        location_error: 'خطأ في الموقع',
        location_permission_denied: 'تم رفض إذن الموقع',
        location_unavailable: 'الموقع غير متاح',
        location_timeout: 'انتهت مهلة طلب الموقع',
        location_error_generic: 'حدث خطأ أثناء الحصول على موقعك.',
        location_permission_help: 'لتفعيل خدمات الموقع، اذهب إلى إعدادات جهازك واسمح بالوصول للموقع لهذا التطبيق.',
        btn_manual_location: 'إدخال الموقع يدوياً',
        btn_retry: 'إعادة المحاولة',
        btn_cancel: 'إلغاء',
        manual_location_title: 'تحديد موقعك',
        manual_location_desc: 'أدخل مدينتك ودولتك للحصول على أوقات صلاة دقيقة.',
        quick_select_cities: 'اختيار سريع',
        label_city: 'المدينة',
        label_country: 'الدولة',
        label_use_coordinates: 'أعرف الإحداثيات الدقيقة',
        label_latitude: 'خط العرض',
        label_longitude: 'خط الطول',
        placeholder_city: 'أدخل مدينتك',
        placeholder_country: 'أدخل دولتك',
        error_city_required: 'المدينة مطلوبة',
        error_country_required: 'الدولة مطلوبة',
        error_invalid_latitude: 'خط العرض يجب أن يكون بين -90 و 90',
        error_invalid_longitude: 'خط الطول يجب أن يكون بين -180 و 180',
        btn_set_location: 'تحديد الموقع',
        btn_reset: 'إعادة تعيين',
        location_loading: 'جاري الحصول على الموقع...',
        location_not_set: 'لم يتم تحديد الموقع',
        location_gps: 'موقع GPS',
        location_manual: 'موقع يدوي',
        location_unknown: 'موقع غير معروف',
        location_tap_to_set: 'اضغط لتحديد موقعك',
        status_gps: 'GPS',
        status_manual: 'يدوي',
        
        // Prayer Times translations
        prayer_times_title: 'أوقات الصلاة',
        todays_prayers: 'صلوات اليوم',
        weekly_prayers: 'أوقات الصلاة الأسبوعية',
        loading_prayer_times: 'جاري تحميل أوقات الصلاة...',
        error_title: 'خطأ',
        retry: 'إعادة المحاولة',
        fajr: 'الفجر',
        sunrise: 'الشروق',
        dhuhr: 'الظهر',
        asr: 'العصر',
        maghrib: 'المغرب',
        isha: 'العشاء',
        next_prayer: 'الصلاة التالية',
        time_remaining: 'الوقت المتبقي',
        
        // Qibla translations
        qibla_title: 'اتجاه القبلة',
        loading_qibla: 'جاري تحديد اتجاه القبلة...',
        qibla_direction: 'اتجاه القبلة',
        distance_to_kaaba: 'المسافة إلى الكعبة',
        compass_calibration: 'معايرة البوصلة',
        calibration_instructions: 'حرك جهازك في شكل رقم 8 لمعايرة البوصلة',
        location_required: 'الموقع مطلوب لتحديد اتجاه القبلة',
        compass_not_supported: 'البوصلة غير مدعومة في هذا الجهاز',
    },
    en: {
        main_title: "Sahw Assistant",
        main_subtitle: "Your guide to the rulings of Sujood As-Sahw in prayer.",
        question_type: "What type of mistake occurred?",
        btn_increase: "Addition",
        btn_decrease: "Omission",
        btn_doubt: "Doubt",
        q_decrease_type: "What was omitted?",
        q_decrease_desc: "A Rukn (pillar) is an essential part of the prayer, invalid without it (e.g., bowing, prostrating). A Wajib (obligation) is something that invalidates the prayer if left intentionally, but not if forgotten (e.g., the first Tashahhud).",
        btn_decrease_wajib: "Omitted an Obligation (Wajib)",
        btn_decrease_rukn: "Omitted a Pillar (Rukn)",
        q_doubt_type: "Are you more certain about one choice?",
        q_doubt_desc: "Do you have a strong feeling about the number of rak'ahs (e.g., you strongly feel you prayed three, not four)?",
        btn_doubt_yes: "Yes, I have a strong feeling",
        btn_doubt_no: "No, I am completely unsure",
        result_title: "The Ruling",
        btn_start_over: "Start Over",
        btn_back: "Back",
        daleel_title: "Evidence from the Sunnah",
        increase_title: "Ruling in Case of Addition",
        increase_details: `<p class="mb-2">If you mistakenly add a bow, prostration, or a full rak'ah to your prayer, your prayer is still valid.</p><ul class="list-disc list-inside space-y-2"><li>Complete your prayer until the Tasleem.</li><li>After the Tasleem, perform two prostrations for forgetfulness.</li><li>Then, make the Tasleem again.</li></ul>`,
        increase_daleel: `The hadith of Abdullah ibn Mas'ud (may Allah be pleased with him) that the Prophet (ﷺ) prayed Dhuhr with five rak'ahs. When asked, "Has the prayer been increased?" He said, "What is that?" They said, "You prayed five." So he performed two prostrations after he had made the Tasleem. (Agreed upon).`,
        decrease_wajib_title: "Ruling in Case of Omitting an Obligation (Wajib)",
        decrease_wajib_details: `<p class="mb-2">If you forget an obligation (like the first Tashahhud) and remember it after moving to the next pillar, do not go back.</p><ul class="list-disc list-inside space-y-2"><li>Continue your prayer as normal.</li><li>Before making the final Tasleem, perform two prostrations for forgetfulness.</li><li>Then, make the Tasleem.</li></ul>`,
        decrease_wajib_daleel: `The hadith of Abdullah ibn Buhaynah (may Allah be pleased with him) that the Prophet (ﷺ) stood up after two rak'ahs in Dhuhr without sitting. When he finished his prayer... he performed two prostrations before the Tasleem, then made the Tasleem. (Agreed upon).`,
        decrease_rukn_title: "Ruling in Case of Omitting a Pillar (Rukn)",
        decrease_rukn_details: `<p class="mb-2 text-red-600 font-semibold">Omitting a pillar is a serious mistake and is not fixed by the two prostrations alone.</p><p class="mb-2">You must perform the pillar you missed and what comes after it. If you don't, your prayer is invalid.</p><ul class="list-disc list-inside space-y-2"><li>If you remember before reaching its place in the next rak'ah, you must immediately return to perform it and what follows.</li><li>If you remember after reaching its place in the next rak'ah, the rak'ah in which you missed the pillar is nullified, and the current rak'ah takes its place.</li><li>In both cases, you complete your prayer and then perform two prostrations for forgetfulness before the Tasleem.</li></ul>`,
        decrease_rukn_daleel: `A general principle in Fiqh: "A pillar is not waived due to forgetfulness, nor is it compensated for by Sujood As-Sahw." This is supported by the hadith of the "man who prayed badly," whom the Prophet (ﷺ) commanded to repeat the prayer for omitting a pillar (tranquility), and did not just tell him to perform Sujood As-Sahw.`,
        doubt_prevail_title: "Ruling in Case of Doubt with Stronger Inclination",
        doubt_prevail_details: `<p class="mb-2">If you are in doubt about the number of rak'ahs but have a stronger feeling towards one number.</p><ul class="list-disc list-inside space-y-2"><li>Act upon what you are more certain of and complete your prayer.</li><li>After making the final Tasleem, perform two prostrations for forgetfulness.</li><li>Then, make the Tasleem again.</li></ul>`,
        doubt_prevail_daleel: `The hadith of Ibn Mas'ud (may Allah be pleased with him) that the Prophet (ﷺ) said: "If any of you is in doubt during his prayer, he should aim for what is correct, complete his prayer upon it, then make the Tasleem, and then perform two prostrations." (Agreed upon).`,
        doubt_no_prevail_title: "Ruling in Case of Doubt without Stronger Inclination",
        doubt_no_prevail_details: `<p class="mb-2">If you are in doubt about the number of rak'ahs and are not more certain of either choice.</p><ul class="list-disc list-inside space-y-2"><li>Act upon certainty, which is the lesser number (e.g., if in doubt between three and four, assume it is three).</li><li>Complete your prayer based on that.</li><li>Before making the final Tasleem, perform two prostrations for forgetfulness.</li><li>Then, make the Tasleem.</li></ul>`,
        doubt_no_prevail_daleel: `The hadith of Abu Sa'id al-Khudri (may Allah be pleased with him) who said: The Messenger of Allah (ﷺ) said: "If any of you is in doubt in his prayer and does not know how many he has prayed, three or four, he should cast aside the doubt and build on what is certain, then perform two prostrations before the Tasleem...". (Narrated by Muslim).`,
        
        // Location-related translations
        location_error: 'Location Error',
        location_permission_denied: 'Location Permission Denied',
        location_unavailable: 'Location Unavailable',
        location_timeout: 'Location Request Timeout',
        location_error_generic: 'An error occurred while getting your location.',
        location_permission_help: 'To enable location services, go to your device settings and allow location access for this app.',
        btn_manual_location: 'Enter Location Manually',
        btn_retry: 'Try Again',
        btn_cancel: 'Cancel',
        manual_location_title: 'Set Your Location',
        manual_location_desc: 'Enter your city and country to get accurate prayer times.',
        quick_select_cities: 'Quick Select',
        label_city: 'City',
        label_country: 'Country',
        label_use_coordinates: 'I know the exact coordinates',
        label_latitude: 'Latitude',
        label_longitude: 'Longitude',
        placeholder_city: 'Enter your city',
        placeholder_country: 'Enter your country',
        error_city_required: 'City is required',
        error_country_required: 'Country is required',
        error_invalid_latitude: 'Latitude must be between -90 and 90',
        error_invalid_longitude: 'Longitude must be between -180 and 180',
        btn_set_location: 'Set Location',
        btn_reset: 'Reset',
        location_loading: 'Getting location...',
        location_not_set: 'Location not set',
        location_gps: 'GPS Location',
        location_manual: 'Manual Location',
        location_unknown: 'Unknown location',
        location_tap_to_set: 'Tap to set your location',
        status_gps: 'GPS',
        status_manual: 'Manual',
        
        // Prayer Times translations
        prayer_times_title: 'Prayer Times',
        todays_prayers: "Today's Prayers",
        weekly_prayers: 'Weekly Prayer Times',
        loading_prayer_times: 'Loading prayer times...',
        error_title: 'Error',
        retry: 'Retry',
        fajr: 'Fajr',
        sunrise: 'Sunrise',
        dhuhr: 'Dhuhr',
        asr: 'Asr',
        maghrib: 'Maghrib',
        isha: 'Isha',
        next_prayer: 'Next Prayer',
        time_remaining: 'Time Remaining',
        
        // Qibla translations
        qibla_title: 'Qibla Direction',
        loading_qibla: 'Loading qibla direction...',
        qibla_direction: 'Qibla Direction',
        distance_to_kaaba: 'Distance to Kaaba',
        compass_calibration: 'Compass Calibration',
        calibration_instructions: 'Move your device in a figure-8 pattern to calibrate the compass',
        location_required: 'Location required for qibla direction',
        compass_not_supported: 'Compass not supported on this device',
    }
};
